micronaut:
  application:
    name: split-expense-api
  server:
    port: 8080
  views:
    handlebars:
      enabled: true
  openapi:
    views:
      spec: swagger-ui.hbs
    schema:
      generate: "true"
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**


datasources:
  default:
    url: jdbc:postgresql://localhost:5432/splitexpense
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'sa'
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true



jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

netty:
  default:
    allocator:
      max-order: 3

app:
  hello: "Hello World"